### ISSUE TITLE
Provide Documentation of usage

### ISSUE THREAD

**Issue by devendra1102** [buraktt/sails-hook-blueprint-filters#1]
Hello, I have installed this hook.But I don't know how to use this. When I ping on `/:model/filters`  it returns just : 
`{
filters: [ ]
}` for every model. How do I get the filter?

**Comment by buraktt** [comment]
@devendra1102 
I merged filter hooks to [sercanov/sails-hook-blueprint-utils](https://github.com/sercanov/sails-hook-blueprint-utils)
It's more functional & better documented.

**Comment by devendra1102** [comment]
@buraktt ok thanks
